:bug: 役職一覧に村人や人狼が2回表示される場合がある問題の修正を行った
nocox/one-night-jinroh pull request #136
Opened 2024-05-11 07:47 UTC by kuniyuki-f

直りました
![image](https://github.com/nocox/one-night-jinroh/assets/9443634/8f9475aa-87e7-4f1f-9b3b-fd5f7647b734)

2024-05-11 07:50 UTC, kuniyuki-f reviewed
@nocox 
バグ修正しました。
ロジックやコンポーネントを変更したのでレビューお願いします

2024-05-11 07:50 UTC, kuniyuki-f commented on react/src/features/room/components/GameStartModal/RoleListWithCount.tsx
> +import { css } from 'styled-system/css';
役職一覧のところ集計ロジックも含めて外部からは参照しないコンポーネントに切り出しました。
index.tsからexportしないのでGameStartModalからしか参照しない、という感じです

2024-05-11 07:50 UTC, kuniyuki-f commented on react/src/features/room/components/GameStartModal/RoleListWithCount.tsx
> +    }, {});
roleIdでソートしてから役職ごとに数を数えてRecord作成しています。
例えば、['村人', 2]みたいな要素の配列ができます。
複雑なRecordではないので、型定義などは行わずTSXでは配列の添字で直接参照してます。

2024-05-11 08:13 UTC, nocox reviewed
レビューしました。

2024-05-11 08:13 UTC, nocox commented on react/src/features/room/components/GameStartModal/RoleListWithCount.tsx
> +  const roleCount = roleList
roleCountだと数字だけを持っていそうなので、組み合わせを持っていることを強調する名前にすると良いかも。

2024-05-11 08:19 UTC, nocox requested changes
追加コメントです。
次回忘れないために、Request changesにしておきます。

2024-05-11 08:19 UTC, nocox commented on react/src/features/room/components/GameStartModal/RoleListWithCount.tsx
> +    }, {});
role[0]とrole[1]に何が入っているかわかりにくきがしたので、何かやった方が良さそう。

この辺りが選択肢になりそうです。
- コメントで、roleにどんな値が入るのかを示す
- 型を作る
- role自体を辞書型で定義する。nameとcount的な感じで
- countだけ別で扱う。

2024-05-12 07:45 UTC, kuniyuki-f commented on react/src/features/room/components/GameStartModal/RoleListWithCount.tsx
> +  const roleCount = roleList
@nocox 
f3d2b2f3c7957d0b86974aefda3bdf76bca2a0d7
こちらのコミットで命名変更しました！

2024-05-12 07:48 UTC, kuniyuki-f commented on react/src/features/room/components/GameStartModal/RoleListWithCount.tsx
> +    }, {});
@nocox 
982243821aa8da9ac89e682655cd814e29b36d4c
groupBy をエディタで認識できるようにするのが大変そうだったので、一旦型定義と関数切り出しで対応しました。
結局、JSX部分がrole＋添え字になってしまっているけど、前よりはわかりやすくなった・・・のかな。
一応`groupBy`の返り値は `Object.groupBy` と同じような形にしました。

2024-05-12 07:49 UTC, kuniyuki-f commented
@nocox 

https://github.com/nocox/one-night-jinroh/pull/136#discussion_r1597574334
https://github.com/nocox/one-night-jinroh/pull/136#discussion_r1597574334

レビューありがとう！
コメントもらってる件については上記で返信してます。

また具体的な議論は次回開発会の時にでもやれればと思います👍

2024-06-01 05:46 UTC, kuniyuki-f commented on react/src/features/room/components/GameStartModal/RoleListWithCount.tsx
> +    }, {});
> role[0]とrole[1]に何が入っているか

deff00c87f8c47b7cfb2081849db283c0c67ac81 で値を明示的な変数名に分割代入するよう修正しました。

2024-06-01 07:00 UTC, nocox approved these changes
@kuniyuki-f 
レビューしました。
コード読んだ感じ動作は問題なさそうなんどえApprovesしちゃいます

2024-06-01 07:00 UTC, nocox commented on react/src/features/room/components/GameStartModal/RoleListWithCount.tsx
> +      acc[role.roleName].push(role);
@kuniyuki-f 
ここでpushでrole入れるのではなく、countしちゃえば良いと思いました。
roleをこの後使うことはないと思ったので

2024-06-01 07:20 UTC, kuniyuki-f commented on react/src/features/room/components/GameStartModal/RoleListWithCount.tsx
> +      acc[role.roleName].push(role);
@nocox 
c880544f65c4d7bea565f7e03309eb0cae653b2f で修正済みです！

2024-06-01 07:20 UTC, merged